// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYIjivNRUqMBWFh5iAoTOMQVGnqor3OZg',
    appId: '1:396618596567:web:e51daf4258373379563092',
    messagingSenderId: '396618596567',
    projectId: 'github-mobile-app',
    authDomain: 'github-mobile-app.firebaseapp.com',
    storageBucket: 'github-mobile-app.appspot.com',
    measurementId: 'G-XR8XBNMDD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8XM03y3xcRZTHmpeE8ZEBjKy4YOwqmIo',
    appId: '1:396618596567:android:4f407fda3e76215d563092',
    messagingSenderId: '396618596567',
    projectId: 'github-mobile-app',
    storageBucket: 'github-mobile-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZlSZLCMJHQ5PBCYNPzjNft0md0pP1Vio',
    appId: '1:396618596567:ios:ce6025083593c1dd563092',
    messagingSenderId: '396618596567',
    projectId: 'github-mobile-app',
    storageBucket: 'github-mobile-app.appspot.com',
    iosBundleId: 'com.example.githubMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZlSZLCMJHQ5PBCYNPzjNft0md0pP1Vio',
    appId: '1:396618596567:ios:a8eee003b91d85b8563092',
    messagingSenderId: '396618596567',
    projectId: 'github-mobile-app',
    storageBucket: 'github-mobile-app.appspot.com',
    iosBundleId: 'com.example.githubMobileApp.RunnerTests',
  );
}
